steps:
  # Step 1: Build the JAR using Gradle
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['clean', 'build', '-x', 'test']

  # Step 2: Build the Docker image (after JAR is built)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/matematika', '.']

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/matematika']

images:
  - 'gcr.io/$PROJECT_ID/matematika'

options:
  logging: CLOUD_LOGGING_ONLY
