steps:
  - name: 'gcr.io/cloud-builders/gradle'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y openjdk-21-jdk
        export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
        export PATH="$JAVA_HOME/bin:$PATH"
        java -version  # Verify Java version
        ./gradlew clean build
    id: 'Build'

images:
  - 'gcr.io/$PROJECT_ID/matematika'
