steps:
  # Step 1: Use Gradle to build the application
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['clean', 'build', '-x', 'test']
    env:
      - 'JAVA_HOME=/usr/lib/jvm/java-21-openjdk'

  # Step 2: Build the Docker image (using the previously built JAR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/matematika', '.']

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/matematika']

images:
  - 'gcr.io/$PROJECT_ID/matematika'

# Enable Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY
