steps:
  # Step 1: Use the custom Gradle image with Java 21 to build the JAR
  - name: 'gcr.io/$PROJECT_ID/gradle-with-java21'
    args: ['./gradlew', 'clean', 'build', '-x', 'test', '-x', 'bootRun']  # Ensure bootRun is skipped

  # Step 2: Build the Docker image (using the previously built JAR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/matematika', '.']

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/matematika']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'matematika'  # The service name in Cloud Run
      - '--image'
      - 'gcr.io/$PROJECT_ID/matematika'  # The image we pushed to Container Registry
      - '--platform'
      - 'managed'  # Use the managed Cloud Run platform (fully managed, no GKE)
      - '--region'
      - 'europe-north1'  # Or any region you want
      - '--allow-unauthenticated'  # Allow unauthenticated access (remove if not needed)

images:
  - 'gcr.io/$PROJECT_ID/matematika'

options:
  logging: CLOUD_LOGGING_ONLY
